import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Header/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='w-full overflow-x-hidden bg-[#F0F7FF] py-[30px] font-poppins flex flex-col items-center'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
